import { StyleSheet } from 'react-native';
import { couleurs } from './couleurs';

export const globalStyles = StyleSheet.create({
  // Conteneurs
  container: { flex: 1, backgroundColor: couleurs.fond },
  containerCentre: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: couleurs.fond },
  containerPadding: { flex: 1, padding: 20, backgroundColor: couleurs.fond },
  containerSecondaire: { backgroundColor: couleurs.fondSecondaire, borderRadius: 8, padding: 15, marginVertical: 10 },

  // Espacement
  espacementPetit: { margin: 5 },
  espacementMoyen: { margin: 10 },
  espacementGrand: { margin: 20 },
  paddingPetit: { padding: 5 },
  paddingMoyen: { padding: 10 },
  paddingGrand: { padding: 20 },

  // Textes
  titre: { fontSize: 24, fontWeight: 'bold', color: couleurs.textePrimaire, textAlign: 'center' },
  sousTitre: { fontSize: 18, fontWeight: '600', color: couleurs.texteSecondaire, textAlign: 'center', marginBottom: 10 },
  texteCorps: { fontSize: 16, color: couleurs.textePrimaire },
  texteSecondaire: { fontSize: 14, color: couleurs.texteSecondaire },
  texteTertiaire: { fontSize: 12, color: couleurs.texteTertiaire },
  texteErreur: { fontSize: 12, color: couleurs.erreur, marginTop: 4 },
  texteSucces: { fontSize: 14, color: couleurs.succes },

  // Boutons
  bouton: { backgroundColor: couleurs.primaire, paddingVertical: 12, paddingHorizontal: 20, borderRadius: 8, alignItems: 'center', marginVertical: 10 },
  boutonTexte: { color: couleurs.texteInverse, fontSize: 16, fontWeight: '600' },
  boutonDesactive: { backgroundColor: couleurs.bordure },
  boutonSecondaire: { backgroundColor: couleurs.secondaire, paddingVertical: 10, paddingHorizontal: 15, borderRadius: 6, alignItems: 'center' },
  boutonSecondaireTexte: { color: couleurs.texteInverse, fontSize: 14, fontWeight: '500' },

  // Saisies
  saisie: { borderWidth: 1, borderColor: couleurs.bordure, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 14, fontSize: 16, backgroundColor: couleurs.fondSecondaire, color: couleurs.textePrimaire },
  saisieFocus: { borderColor: couleurs.primaire, borderWidth: 2 },
  saisieErreur: { borderColor: couleurs.erreur },
  libelle: { fontSize: 14, color: couleurs.texteSecondaire, marginBottom: 6, fontWeight: '500' },
  groupeFormulaire: { marginBottom: 15, flex: 1 },

  // Cartes
  carte: { backgroundColor: couleurs.fond, borderRadius: 10, padding: 15, marginVertical: 8, shadowColor: couleurs.ombre, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3, borderWidth: 1, borderColor: couleurs.bordureClair },
  carteTitre: { fontSize: 18, fontWeight: 'bold', color: couleurs.textePrimaire, marginBottom: 10 },

  // Layout
  ligne: { flexDirection: 'row', alignItems: 'center' },
  ligneEspace: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  colonne: { flexDirection: 'column' },
  centre: { justifyContent: 'center', alignItems: 'center' },

  // En-têtes
  entete: { backgroundColor: couleurs.secondaire, paddingVertical: 15, paddingHorizontal: 20, borderBottomLeftRadius: 20, borderBottomRightRadius: 20 },
  enteteTitre: { fontSize: 20, fontWeight: 'bold', color: couleurs.texteInverse, textAlign: 'center' },

  // Modales
  overlayModal: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', alignItems: 'center' },
  contenuModal: { backgroundColor: couleurs.fond, borderRadius: 10, padding: 20, width: '80%', maxHeight: '60%' },
  enteteModal: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  titreModal: { fontSize: 18, fontWeight: 'bold', color: couleurs.textePrimaire },

  // Indicateurs
  chargement: { flex: 1, justifyContent: 'center', alignItems: 'center' },

  // Autres
  logo: { width: 120, height: 120 },
  badge: { position: 'absolute', top: 4, right: 4, backgroundColor: couleurs.notificationBadge, borderRadius: 10, width: 18, height: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: couleurs.headerBackground },
  texteBadge: { color: couleurs.texteInverse, fontSize: 10, fontWeight: 'bold' },

  // Header
  headerContainer: { backgroundColor: couleurs.headerBackground, paddingBottom: 15, paddingHorizontal: 20 },
  headerEntete: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 15 },
  headerTitre: { fontSize: 20, fontWeight: 'bold', color: couleurs.headerText },
  boutonNotification: { position: 'relative', padding: 8 },
  contenuNotification: { alignItems: 'center' },
  texteNotification: { fontSize: 16, color: couleurs.modalBackground, textAlign: 'center', marginBottom: 20 },
  boutonVoirListe: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 20, backgroundColor: couleurs.buttonSecondary, borderRadius: 8 },
  texteVoirListe: { fontSize: 16, color: couleurs.texteInverse, fontWeight: '600', marginRight: 8 },

  // ChampFormulaire
  conteneurPicker: { borderWidth: 1, borderColor: couleurs.inputBorder, borderRadius: 8 },
  ageCounter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: couleurs.bordure, borderRadius: 8, paddingVertical: 10, paddingHorizontal: 15, backgroundColor: couleurs.fondSecondaire },
  ageButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: couleurs.primaire, alignItems: 'center', justifyContent: 'center', marginHorizontal: 10 },
  ageButtonDisabled: { backgroundColor: couleurs.bordure, opacity: 0.5 },
  ageButtonText: { color: couleurs.texteInverse, fontSize: 20, fontWeight: 'bold' },
  ageValue: { fontSize: 18, color: couleurs.textePrimaire, minWidth: 30, textAlign: 'center' },

  // Connexion
  loginConteneur: { flex: 1, backgroundColor: couleurs.fond },
  loginEntete: { height: 200, backgroundColor: couleurs.loginBackground, justifyContent: 'center', alignItems: 'center', borderBottomLeftRadius: 30, borderBottomRightRadius: 30 },
  loginFormulaireContainer: { flex: 1, padding: 25, marginTop: 30 },
  loginTitre: { fontSize: 28, fontWeight: 'bold', color: couleurs.loginTitle, marginBottom: 8, textAlign: 'center' },
  loginSousTitre: { fontSize: 16, color: couleurs.loginSubtitle, marginBottom: 20, textAlign: 'center' },
  loginGroupeInput: { marginBottom: 15 },
  loginLabel: { fontSize: 16, fontWeight: '600', color: couleurs.loginLabel, marginBottom: 5 },
  loginInput: { borderWidth: 1, borderColor: couleurs.loginInputBorder, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, fontSize: 16, backgroundColor: couleurs.loginInputBackground },
  loginInputErreur: { borderColor: couleurs.loginError },
  loginTexteErreur: { color: couleurs.loginError, fontSize: 13, marginTop: 3 },
  loginBouton: { backgroundColor: couleurs.loginBackground, paddingVertical: 14, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  loginBoutonDesactive: { backgroundColor: couleurs.buttonDisabled },
  loginTexteBouton: { color: couleurs.texteInverse, fontSize: 16, fontWeight: '600' },

  // Accueil
  accueilContainer: { flex: 1, backgroundColor: couleurs.fondSecondaire },
  accueilLoading: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  accueilScroll: { flex: 1 },
  accueilHeader: { padding: 16 },
  accueilTitle: { fontSize: 24, fontWeight: '700', color: couleurs.textePrimaire },
  accueilSubtitle: { fontSize: 15, color: couleurs.texteTertiaire, marginTop: 4 },
  accueilTopRow: { backgroundColor: couleurs.fond, marginHorizontal: 16, borderRadius: 12, padding: 20, flexDirection: 'row' },
  accueilTopCard: { flex: 1, alignItems: 'center' },
  accueilTopNumber: { fontSize: 28, fontWeight: '600', color: couleurs.textePrimaire },
  accueilTopLabel: { fontSize: 14, color: couleurs.texteTertiaire, marginTop: 4 },
  accueilMiddleCard: { backgroundColor: couleurs.fond, marginHorizontal: 16, marginTop: 12, borderRadius: 12, padding: 20, flexDirection: 'row' },
  accueilMiddleLeft: { flex: 1, paddingRight: 16 },
  accueilMiddleRight: { flex: 1, paddingLeft: 16 },
  accueilSectionTitle: { fontSize: 16, fontWeight: '600', color: couleurs.textePrimaire, marginBottom: 12 },
  accueilScolItem: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  accueilDot: { width: 12, height: 12, borderRadius: 6 },
  accueilDotOk: { backgroundColor: couleurs.succes },
  accueilDotNot: { backgroundColor: couleurs.erreur },
  accueilScolText: { fontSize: 14, color: couleurs.texteTertiaire, flex: 1 },
  accueilScolNumber: { fontSize: 16, fontWeight: '600', color: couleurs.textePrimaire },
  accueilNatItem: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  accueilNatDot: { width: 12, height: 12, borderRadius: 6 },
  accueilNatText: { fontSize: 14, color: couleurs.texteTertiaire, flex: 1 },
  accueilNatNumber: { fontSize: 16, fontWeight: '600', color: couleurs.textePrimaire },
  accueilRecent: { backgroundColor: couleurs.fond, marginHorizontal: 16, marginTop: 12, marginBottom: 20, borderRadius: 12, padding: 16 },
  accueilRecentHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  accueilRecentTitle: { fontSize: 18, fontWeight: '600', color: couleurs.textePrimaire },
  accueilSeeAll: { fontSize: 15, color: couleurs.primaire, fontWeight: '500' },
  accueilStudent: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, borderTopWidth: 1, borderTopColor: couleurs.bordureClair },
  accueilStudentInfo: { flex: 1 },
  accueilName: { fontSize: 16, fontWeight: '500', color: couleurs.textePrimaire },
  accueilDetails: { fontSize: 14, color: couleurs.texteTertiaire, marginTop: 2 },
  accueilDate: { fontSize: 13, color: couleurs.bordure, marginTop: 2 },
  accueilStatus: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10 },
  accueilStatusOk: { backgroundColor: '#E8F6EF' },
  accueilStatusNot: { backgroundColor: '#FEE' },
  accueilStatusText: { fontSize: 13, fontWeight: '500', color: couleurs.succes },

  // DrawerDesign
  drawerContainer: { flex: 1, backgroundColor: couleurs.fond },
  drawerHeader: { padding: 25, backgroundColor: couleurs.fondSecondaire, borderBottomWidth: 1, borderBottomColor: couleurs.bordureClair, flexDirection: 'row', alignItems: 'center', gap: 15 },
  drawerImageProfil: { width: 60, height: 60, borderRadius: 30, borderWidth: 2, borderColor: couleurs.primaire },
  drawerNom: { fontSize: 18, fontWeight: 'bold', color: couleurs.textePrimaire },
  drawerEmail: { fontSize: 14, color: couleurs.texteTertiaire, marginTop: 4 },
  drawerMenu: { flex: 1, paddingVertical: 10 },
  drawerMenuItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 15, paddingHorizontal: 25, borderBottomWidth: 1, borderBottomColor: couleurs.bordureClair },
  drawerMenuItemLeft: { flexDirection: 'row', alignItems: 'center', gap: 15 },
  drawerMenuTexte: { fontSize: 16, color: couleurs.textePrimaire },
  drawerSousMenu: { backgroundColor: couleurs.fondSecondaire, paddingLeft: 45 },
  drawerSousMenuItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12, paddingHorizontal: 20, borderBottomWidth: 1, borderBottomColor: couleurs.bordureClair },
  drawerDeconnexionBtn: { flexDirection: 'row', alignItems: 'center', gap: 15, padding: 25, borderTopWidth: 1, borderTopColor: couleurs.bordureClair, backgroundColor: couleurs.fondSecondaire },
  drawerDeconnexionTexte: { fontSize: 16, color: couleurs.erreur, fontWeight: '600' },
  drawerModalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.8)', justifyContent: 'center', alignItems: 'center' },
  drawerModalCloseArea: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  drawerModalContent: { position: 'relative', alignItems: 'center' },
  drawerCloseBtn: { position: 'absolute', top: -40, right: 0, zIndex: 1 },
  drawerLargeImage: { width: 250, height: 250, borderRadius: 125, borderWidth: 4, borderColor: couleurs.fond },

  // Etudiants
  etudiantsContainer: { flex: 1, backgroundColor: couleurs.fondSecondaire },
  etudiantsLoading: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  etudiantsScroll: { flex: 1 },
  etudiantsHeaderSection: { padding: 16, backgroundColor: couleurs.fond },
  etudiantsSearchRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  etudiantsSearchBox: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: couleurs.fondSecondaire, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, gap: 8, borderWidth: 1, borderColor: couleurs.bordureClair },
  etudiantsSearchInput: { flex: 1, fontSize: 16, color: couleurs.textePrimaire },
  etudiantsAddBtn: { backgroundColor: couleurs.primaire, width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center' },
  etudiantsInfoSection: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 16, backgroundColor: couleurs.fond, marginTop: 8 },
  etudiantsTotalText: { fontSize: 16, color: couleurs.textePrimaire, fontWeight: '600' },
  etudiantsExportBtn: { paddingHorizontal: 12, paddingVertical: 8 },
  etudiantsExportText: { fontSize: 15, color: couleurs.primaire, fontWeight: '500' },
  etudiantsStudentCard: { backgroundColor: couleurs.fond, marginHorizontal: 16, marginBottom: 8, padding: 12, borderRadius: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: couleurs.bordureClair },
  etudiantsStudentMain: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  etudiantsAvatar: { width: 44, height: 44, borderRadius: 22, marginRight: 12 },
  etudiantsStudentInfo: { flex: 1 },
  etudiantsStudentName: { fontSize: 15, fontWeight: '600', color: couleurs.textePrimaire, marginBottom: 2 },
  etudiantsStudentDetails: { fontSize: 13, color: couleurs.texteTertiaire },
  etudiantsStudentActions: { flexDirection: 'row', gap: 8 },
  etudiantsActionBtn: { padding: 6 },

  // Inscriptions (première occurrence)
  inscriptionsContainer: { flex: 1, backgroundColor: couleurs.fondSecondaire },
  inscriptionsLoading: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  inscriptionsScroll: { flex: 1 },
  inscriptionsHeaderSection: { padding: 16, backgroundColor: couleurs.fond },
  inscriptionsSearchBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: couleurs.fondSecondaire, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, gap: 8, borderWidth: 1, borderColor: couleurs.bordureClair },
  inscriptionsSearchInput: { flex: 1, fontSize: 16, color: couleurs.textePrimaire },
  inscriptionsTabs: { flexDirection: 'row', backgroundColor: couleurs.fond, paddingHorizontal: 16, borderBottomWidth: 1, borderBottomColor: couleurs.bordureClair },
  inscriptionsTab: { flex: 1, paddingVertical: 16, alignItems: 'center' },
  inscriptionsTabText: { fontSize: 16, color: couleurs.texteTertiaire, fontWeight: '500' },
  inscriptionsActiveTabText: { color: couleurs.primaire, fontWeight: '600' },
  inscriptionsTabIndicator: { position: 'absolute', bottom: 0, width: '100%', height: 2, backgroundColor: couleurs.primaire },
  inscriptionsSection: { backgroundColor: couleurs.fond, marginHorizontal: 16, marginTop: 8, borderRadius: 12, padding: 16 },
  inscriptionsStudentCard: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderTopWidth: 1, borderTopColor: couleurs.bordureClair },
  inscriptionsAvatar: { width: 40, height: 40, borderRadius: 20, marginRight: 12 },
  inscriptionsStudentName: { fontSize: 16, color: couleurs.textePrimaire },
  inscriptionsEmptyText: { textAlign: 'center', color: couleurs.texteTertiaire, paddingVertical: 24 },

  // DetailsEtudiant
  detailsEtudiantContainer: { flex: 1, backgroundColor: couleurs.fondSecondaire },
  detailsEtudiantScroll: { flex: 1, padding: 12 },
  detailsEtudiantCenter: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  detailsEtudiantCardRow: { backgroundColor: couleurs.fond, padding: 12, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 12 },
  detailsEtudiantAvatar: { width: 60, height: 60, borderRadius: 30 },
  detailsEtudiantNom: { fontSize: 17, fontWeight: '600', color: couleurs.textePrimaire },
  detailsEtudiantBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 14 },
  detailsEtudiantActions: { flexDirection: 'row', backgroundColor: couleurs.fond, marginTop: 12, paddingVertical: 12, justifyContent: 'space-around', borderRadius: 12 },
  detailsEtudiantActionBtn: { alignItems: 'center' },
  detailsEtudiantActionTxt: { fontSize: 12, color: couleurs.texteTertiaire, marginTop: 4 },
  detailsEtudiantSection: { backgroundColor: couleurs.fond, marginTop: 12, padding: 16, borderRadius: 12 },
  detailsEtudiantSectionTitle: { fontSize: 15, fontWeight: '600', color: couleurs.primaire, marginBottom: 10 },
  detailsEtudiantRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: couleurs.bordureClair },
  detailsEtudiantLabel: { fontSize: 14, color: couleurs.texteTertiaire },
  detailsEtudiantValue: { fontSize: 14, color: couleurs.textePrimaire, fontWeight: '500' },
  detailsEtudiantFooter: { position: 'absolute', bottom: 20, left: 0, right: 0, alignItems: 'center' },
  detailsEtudiantBackBtn: { backgroundColor: couleurs.bordure, paddingVertical: 14, paddingHorizontal: 40, borderRadius: 14 },
  detailsEtudiantBackTxt: { fontSize: 16, fontWeight: '600', color: couleurs.textePrimaire },
  detailsEtudiantModalBg: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.8)', justifyContent: 'center', alignItems: 'center' },
  detailsEtudiantModalCloseZone: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  detailsEtudiantModalContent: { position: 'relative', alignItems: 'center' },
  detailsEtudiantModalCloseBtn: { position: 'absolute', top: -40, right: 0, zIndex: 1 },
  detailsEtudiantBigAvatar: { width: 220, height: 220, borderRadius: 110, borderWidth: 3, borderColor: couleurs.fond },

  // FormulaireEtudiant
  formulaireEtudiantScroll: { flex: 1, backgroundColor: couleurs.fondSecondaire },
  formulaireEtudiantSectionFormulaire: { backgroundColor: couleurs.fond, margin: 16, borderRadius: 12, padding: 20 },
  formulaireEtudiantLigneFormulaire: { flexDirection: 'row', gap: 12, marginBottom: 4 },
  formulaireEtudiantActionsFormulaire: { flexDirection: 'row', gap: 12, marginTop: 4 },
  formulaireEtudiantBoutonSoumettre: { backgroundColor: couleurs.primaire, paddingVertical: 14, borderRadius: 8, alignItems: 'center', flex: 1 },
  formulaireEtudiantTexteSoumettre: { color: couleurs.texteInverse, fontSize: 16, fontWeight: '500' },
  formulaireEtudiantBoutonAnnuler: { backgroundColor: couleurs.bordureClair, paddingVertical: 14, borderRadius: 8, alignItems: 'center', flex: 1 },
  formulaireEtudiantTexteAnnuler: { color: couleurs.texteTertiaire, fontSize: 16, fontWeight: '500' },

  // Historique
  historiqueContainer: { flex: 1, backgroundColor: couleurs.fondSecondaire },
  historiqueLoading: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  historiqueSearchSection: { flexDirection: 'row', alignItems: 'center', backgroundColor: couleurs.fond, margin: 16, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 10, gap: 8 },
  historiqueSearchInput: { flex: 1, fontSize: 16, color: couleurs.textePrimaire },
  historiqueScroll: { flex: 1, marginTop: 8 },
  historiqueItem: { backgroundColor: couleurs.fond, marginHorizontal: 16, marginBottom: 8, padding: 14, borderRadius: 10, shadowColor: couleurs.ombre, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1, flexDirection: 'row', alignItems: 'center' },
  historiqueAvatar: { width: 40, height: 40, borderRadius: 20, marginRight: 12 },
  historiqueItemContent: { flex: 1 },
  historiqueItemHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  historiqueItemName: { fontSize: 16, fontWeight: '600', color: couleurs.textePrimaire },
  historiqueItemAction: { fontSize: 14, color: couleurs.primaire, fontWeight: '500' },
  historiqueItemDate: { fontSize: 14, color: couleurs.texteTertiaire },
  historiqueEmpty: { alignItems: 'center', marginTop: 64 },
  historiqueEmptyText: { fontSize: 16, color: couleurs.texteTertiaire, marginTop: 12 },

  // Archive
  archiveContainer: { flex: 1, backgroundColor: couleurs.fondSecondaire },
  archiveLoading: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  archiveHeaderSection: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 16 },
  archiveCount: { fontSize: 15, color: couleurs.texteTertiaire },
  archiveScroll: { flex: 1 },
  archiveItem: { backgroundColor: couleurs.fond, marginHorizontal: 16, marginBottom: 8, padding: 12, borderRadius: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  archiveAvatar: { width: 40, height: 40, borderRadius: 20, marginRight: 12 },
  archiveItemContent: { flex: 1 },
  archiveName: { fontSize: 15, fontWeight: '600', color: couleurs.textePrimaire, marginBottom: 2 },
  archiveDetails: { fontSize: 13, color: couleurs.texteTertiaire, marginBottom: 2 },
  archiveDate: { fontSize: 12, color: couleurs.primaire },
  archiveRestoreBtn: { backgroundColor: couleurs.succes, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  archiveRestoreText: { fontSize: 14, color: couleurs.texteInverse, fontWeight: '500' },
  archiveEmpty: { alignItems: 'center', marginTop: 64 },
  archiveEmptyText: { fontSize: 16, color: couleurs.texteTertiaire },

  // ModifierEtudiant
  modifierEtudiantScroll: { flex: 1 },
  modifierEtudiantSectionFormulaire: { backgroundColor: couleurs.fond, marginHorizontal: 16, marginTop: 12, borderRadius: 12, padding: 20 },
  modifierEtudiantLigneFormulaire: { flexDirection: 'row', gap: 12, marginBottom: 8 },
  modifierEtudiantActionsFormulaire: { flexDirection: 'row', gap: 12, marginTop: 8 },
  modifierEtudiantBoutonSoumettre: { backgroundColor: couleurs.primaire, paddingVertical: 14, borderRadius: 8, alignItems: 'center', flex: 1 },
  modifierEtudiantTexteSoumettre: { color: couleurs.texteInverse, fontSize: 16, fontWeight: '500' },
  modifierEtudiantBoutonAnnuler: { backgroundColor: couleurs.bordureClair, paddingVertical: 14, borderRadius: 8, alignItems: 'center', flex: 1 },
  modifierEtudiantTexteAnnuler: { color: couleurs.texteTertiaire, fontSize: 16, fontWeight: '500' },

  // Profil
  profilEcran: { flex: 1, backgroundColor: couleurs.fondSecondaire },
  profilChargement: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  profilScroll: { flex: 1 },
  profilSectionHaut: { alignItems: 'center', padding: 30, backgroundColor: couleurs.fond },
  profilPhoto: { width: 90, height: 90, borderRadius: 45, borderWidth: 2, borderColor: couleurs.bordureClair },
  profilNomUtilisateur: { fontSize: 20, fontWeight: '600', color: couleurs.textePrimaire, marginTop: 12 },
  profilEmailUtilisateur: { fontSize: 15, color: couleurs.texteTertiaire, marginTop: 4 },
  profilCarte: { backgroundColor: couleurs.fond, marginHorizontal: 16, marginTop: 8, borderRadius: 12, padding: 20 },
  profilTitreSection: { fontSize: 17, fontWeight: '600', color: couleurs.textePrimaire, marginBottom: 20 },
  profilChamp: { marginBottom: 16 },
  profilLabelChamp: { fontSize: 13, color: couleurs.texteTertiaire, marginBottom: 6, fontWeight: '500' },
  profilTexteChamp: { fontSize: 17, color: couleurs.textePrimaire },
  profilInputChamp: { fontSize: 17, borderWidth: 1, borderColor: couleurs.bordureClair, borderRadius: 8, padding: 10, color: couleurs.textePrimaire },
  profilSeparateur: { height: 1, backgroundColor: couleurs.bordureClair, marginVertical: 12 },
  profilActions: { flexDirection: 'row', gap: 12, marginTop: 24 },
  profilBoutonEdition: { flexDirection: 'row', alignItems: 'center', backgroundColor: couleurs.fondSecondaire, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 8, gap: 8, flex: 1, justifyContent: 'center' },
  profilTexteBoutonEdition: { fontSize: 16, fontWeight: '500', color: couleurs.primaire },
  profilBoutonPrincipal: { backgroundColor: couleurs.primaire, paddingVertical: 14, borderRadius: 8, alignItems: 'center', flex: 1 },
  profilTexteBoutonPrincipal: { fontSize: 16, fontWeight: '500', color: couleurs.texteInverse },
  profilBoutonSecondaire: { backgroundColor: couleurs.bordureClair, paddingVertical: 14, borderRadius: 8, alignItems: 'center', flex: 1 },
  profilTexteBoutonSecondaire: { fontSize: 16, fontWeight: '500', color: couleurs.texteTertiaire },
  profilFondModal: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.8)', justifyContent: 'center', alignItems: 'center' },
  profilZoneFermerModal: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  profilContenuModal: { position: 'relative', alignItems: 'center' },
  profilBoutonFermer: { position: 'absolute', top: -40, right: 0, zIndex: 1 },
  profilGrandeImage: { width: 250, height: 250, borderRadius: 125, borderWidth: 4, borderColor: couleurs.fond },

  // ChangerMotDePasse
  changerMotDePasseContainer: { flex: 1, backgroundColor: couleurs.fondSecondaire },
  changerMotDePasseScroll: { flex: 1 },
  changerMotDePasseForm: { backgroundColor: couleurs.fond, marginTop: 8, padding: 16 },
  changerMotDePasseField: { marginBottom: 16 },
  changerMotDePasseLabel: { fontSize: 13, color: couleurs.texteTertiaire, marginBottom: 6, fontWeight: '500' },
  changerMotDePasseInput: { fontSize: 17, borderWidth: 1, borderColor: '#000000', borderRadius: 8, padding: 12, color: couleurs.textePrimaire },
  changerMotDePasseButton: { backgroundColor: couleurs.primaire, paddingVertical: 14, borderRadius: 8, alignItems: 'center', marginTop: 8 },
  changerMotDePasseDisabled: { backgroundColor: couleurs.buttonDisabled },
  changerMotDePasseButtonText: { color: couleurs.texteInverse, fontSize: 16, fontWeight: '600' },

  // Parametres
  parametresContainer: { flex: 1, backgroundColor: couleurs.fondSecondaire },
  parametresContent: { padding: 20 },
  parametresTitle: { fontSize: 20, fontWeight: 'bold', color: couleurs.textePrimaire, marginBottom: 20, textAlign: 'left' },
  parametresSettingButton: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: couleurs.fond, padding: 15, borderRadius: 8, marginBottom: 10 },
  parametresSettingInfo: { flexDirection: 'row', alignItems: 'center', gap: 15 },
  parametresSettingText: { fontSize: 16, color: couleurs.textePrimaire },
  parametresVersion: { alignItems: 'center', marginTop: 30 },
  parametresVersionText: { color: couleurs.texteTertiaire, fontSize: 14 },
  parametresModalContainer: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', alignItems: 'center' },
  parametresModalContent: { backgroundColor: couleurs.fond, borderRadius: 10, padding: 20, width: '80%', maxHeight: '70%' },
  parametresModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  parametresModalTitle: { fontSize: 18, fontWeight: 'bold', color: couleurs.textePrimaire },
  parametresModalText: { fontSize: 16, color: couleurs.texteSecondaire, lineHeight: 24 },
});